Source/Networking.swift
Tests/Tests/Tests.swift

Logs networking errors
```
========== Networking Error ==========
Error 3840: Error Domain=NSCocoaErrorDomain Code=3840 "JSON text did not start with array or object and option to allow fragments not set." UserInfo={NSDebugDescription=JSON text did not start with array or object and option to allow fragments not set.}
Path: http://httpbin.org/posdddddt
Response: <NSHTTPURLResponse: 0x7f8e19f28920> { URL: http://httpbin.org/posdddddt } { status code: 404, headers {
"Access-Control-Allow-Credentials" = true;
"Access-Control-Allow-Origin" = "*";
Connection = "keep-alive";
"Content-Length" = 233;
"Content-Type" = "text/html";
Date = "Thu, 08 Oct 2015 12:52:58 GMT";
Server = nginx;
} }
Params: {
password = password;
username = jameson;
}
Data: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 …
```

Feature: logger

---

Source/Networking+HTTPRequest.swift
Source/Networking+Image.swift
Source/Networking.swift
Tests/HTTPRequestTests.swift
Tests/ImageTests.swift
Tests/Tests.swift

Fixes #54
Not only adds the feature of stubbing failures but also adds support for returning custom status codes in the stubbed responses. If the response is different than 2XX it will create a NSError with the error.

Feature: stub failures

---

README.md
Source/Networking+HTTPRequest.swift
Source/Networking+Image.swift
Source/Networking.swift
Tests/HTTPRequestTests.swift
Tests/ImageTests.swift

Helps this feature to be more accessible to users that don’t need much introduction into what stubbing or mocking means.

Rename stub to fake

---

README.md
Source/Networking.swift
Tests/Tests.swift

This PR adds support for HTTP Token Authentication (Authorization: Token token=Pm1xbWcXBUe5HmEhNXnMndVM).
I'm open to a better way of specifying which type of token to use. In this version of the code simply passing `token=` as part of the string in the `authenticate` method triggers HTTP Token support.
Bearer Token usage remains the same.
```swift
let networking = Networking(baseURL: "http://sample.org")
networking.authenticate("token=AAAFFAAAA3DAAAAAA")
networking.GET("/users", completion: { JSON, error in
// Do something...
})
```

Initial Support for HTTP Token Authentication

---

README.md
Sources/Networking+HTTPRequest.swift
Sources/Networking.swift
Tests/HTTPRequestTests.swift

The HTTP specification is so unfriendly, you have to know the specifics of it before understanding that content type is really just the parameter type. Anyway, here's hoping this makes it more human friendly.

Rename ContentType to ParameterType

---

Sources/Networking.swift
Tests/HTTPRequestTests.swift

After a Networking error happened it tried to serialize an empty JSON, throwing a Cocoa Serialization error instead of a Networking one.
- Tests have been improved
- A fix has been added in place

Fix: wrong error return

---

README.md
Sources/Networking.swift
Tests/Helpers.swift
Tests/ImageTests.swift
Tests/NetworkingTests.swift

Also mark them to avoid being uploaded to iCloud. Finally in tvOS just store things in the Caches directory since Documents isn't available there. Fixes #86

Store downloads in documents folder

---

Sources/Networking.swift
Tests/NetworkingTests.swift

Fixes #97
Usage:
```swift
let networking = Networking(baseURL: baseURL)
let key = "Anonymous-Token"
let value = "hi-mom"        
networking.authenticate(headerKey: key, headerValue: value)
networking.POST("/post") { JSON, error in
// Have fun
}
```

Improve support for custom authorization headers

---

Sources/Networking.swift

Removes some optionals and cleans up the logging.
```
========== Networking Error ==========
Error 404: Error Domain=NetworkingErrorDomain Code=404 "not found" UserInfo={NSLocalizedDescription=not found}
Request: <NSMutableURLRequest: 0x10031a250> { URL: http://httpbin.org/posdddddt }
Parameters: Optional("{\n  \"password\" : \"secret\",\n  \"username\" : \"jameson\"\n}")
Data: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.</p>
Headers: ["Accept": "application/json", "Content-Type": "application/json"]
Response status code: 404 — not found
Path: Optional("http://httpbin.org/posdddddt")
Response: …
```

Prettify error logging

---

Sources/Networking+DELETE.swift
Sources/Networking+GET.swift
Sources/Networking+Image.swift
Sources/Networking+POST.swift
Sources/Networking+PUT.swift
Sources/Networking.swift
Sources/TestCheck.swift
Tests/DELETETests.swift
Tests/GETTests.swift
Tests/POSTTests.swift
Tests/PUTTests.swift

Fixes #104
Using `cancelPOST("/post")` would cancel all POST request for the specific path, but in some cases this isn't what we want, for example trying to cancel one request when creating two resources at the same time, you would use the same path but different parameters, this is when ID based cancellation is useful.
```swift
let networking = Networking(baseURL: "http://httpbin.org")
let firstRequestID = networking.POST("/post", parameters: ["username" : "3lvis"]) { JSON, error in
// result
}
let secondRequestID = networking.POST("/post", parameters: ["username" : "sgl0v"]) { JSON, error in
// result
}
networking.cancel(firstRequestID)
```
The great thing is that you don't want to use the ID, you just ignore it. So this still works without warnings.
```swift
let networking = …
```

Improve request cancellation with ID

---

Sources/Networking.swift

Returning JSON data even if an HTTP error occurs. If the HTTP status code is 200 and there is a problem by parsing the JSON it would still return an JSONError.
This would fix #188.

Always return JSON for valid data even if HTTP error occurs.

---

Demo.xcodeproj/project.pbxproj
Demo.xcodeproj/xcshareddata/xcschemes/iOSDemo.xcscheme
Sources/NSFileManager+Helpers.swift
Sources/Networking+DELETE.swift
Sources/Networking+GET.swift
Sources/Networking+Image.swift
Sources/Networking+POST.swift
Sources/Networking+PUT.swift
Sources/Networking.swift
Tests/GETTests.swift
Tests/Helpers.swift
Tests/ImageTests.swift
Tests/NetworkingTests.swift
iOSDemo/AppDelegate.swift
iOSDemo/Assets.xcassets/AppIcon.appiconset/Contents.json
iOSDemo/Base.lproj/LaunchScreen.storyboard
iOSDemo/CellData.swift
iOSDemo/FakeImageController.swift
iOSDemo/Info.plist
iOSDemo/OptionsController.swift

Fixes https://github.com/3lvis/Networking/issues/47
When you use `downloadImage` it gets saved into little files in your caches folder. Thanks to this method you can clean that cache.
```swift
Networking.deleteDownloadedFiles()
```

Support removing cached files

---

Sources/Networking.swift
Tests/NetworkingTests.swift
Tests/POSTTests.swift

`authenticate` is itself a verb, and implies that by calling this method, the user will be authenticated. What in fact happens is that it will setup the next request to have the `basic auth` fields setup.
Did I get that right?
Suggestion for better naming welcome.

Update method name for clarity

---

Demo.xcodeproj/project.pbxproj
Sources/Networking.swift
Sources/String+UTF8.swift
Tests/NetworkingTests.swift
Tests/String+UTF8Tests.swift

If you provided a path that contained special characters, calling destination URL would crash.

Fix issues related to special characters

---

Demo.xcodeproj/project.pbxproj
Sources/Networking.swift
Tests/NetworkingTests.swift
Tests/POSTTests.swift

```swift
public func authenticate(username: String, password: String)
public func authenticate(token: String)
public func authenticate(headerKey: String = "Authorization", headerValue: String)
```
```swift
public func setAuthorizationHeader(username: String, password: String)
public func setAuthorizationHeader(token: String)
public func setAuthorizationHeader(headerKey: String = "Authorization", headerValue: String)
```

Rename authentication method

---

Sources/Networking.swift
Tests/NetworkingTests.swift

```swift
let networking = Networking(baseURL: baseURL)
let requestID = networking.GET("/get") { JSON, error in
//....
}
networking.cancel(with: requestID, completion: nil)
```

Make public to cancel a single request and add a unit test

---

Sources/Networking.swift
Tests/NetworkingTests.swift

```swift 
let networking = Networking(baseURL: baseURL)
networking.headerFields = ["HeaderKey": "HeaderValue"]
networking.POST("/post") { JSON, error in
//.....
}
```
Fixes https://github.com/3lvis/Networking/issues/138

Add support for setting header fields

---

README.md
Sources/Networking+DELETE.swift
Sources/Networking+GET.swift
Sources/Networking+Image.swift
Sources/Networking+POST.swift
Sources/Networking+PUT.swift
Sources/Networking.swift
Tests/DELETETests.swift
Tests/GETTests.swift
Tests/ImageTests.swift
Tests/NetworkingTests.swift
Tests/POSTTests.swift
Tests/PUTTests.swift

As in `URLSessionTask` header:
```
/* -cancel returns immediately, but marks a task as being canceled.
* The task will signal -URLSession:task:didCompleteWithError: with an
* error value of { NSURLErrorDomain, NSURLErrorCancelled }.  In some 
* cases, the task may signal other work before it acknowledges the 
* cancelation.  -cancel may be sent to a task that has been suspended.
*/
```
when a task is cancelled, it will create a `NSError` with code `NSURLErrorCancelled`, which equals to `URLError.cancelled.rawValue`. 
So instead of use hard-coded value `-999` from `HTTPURLResponse.statusCode`, I think we can use `URLError.cancelled` because `-999` is not a standard HTTP status code and it is used only in Apple framework.
// I don't know anything about GitHub checks but all the Xcode tests …

Use URLError.Code for cancelled request instead of -999

---

README.md
Sources/Networking.swift
Tests/NetworkingTests.swift

As requested in #153, adding a simple method to ease adding parameters to URLs for any kind of request.
This is accomplished by adding a new function `addParameters` that leverages the pre-existing `urlEncodedString` extension on `Dictionary`. This minimal change should support any kind of request, and not simply `GET` requests. This design was chosen so as to minimize the surface area of API changes, and to preserve the existing behavior of caches, images, etc.
Documentation and tests are added. All tests still pass.
The updated documentation contains a simple use case using the proposed change:
```swift
let networking = Networking(baseURL: "https://api-news.layervault.com/api/v2")
let path = networking.addParameters(["count": 25], toPath: "/stories")
networking.GET(path) { JSON, error …
```

Adding support for url encoded parameters

---

Sources/FormDataPart.swift
Sources/Networking.swift

This PR fixes the issue https://github.com/3lvis/Networking/issues/176
- multipart body was not being created when parameters were not provided
- optional "filename" for FormDataPart

Fixing Multipart

---

Sources/Result.swift
Tests/ResulTests.swift

Useful for when you don't care about the result but more if there's an error or not.
Before:
```swift
networking.get("/somepath") { result in 
switch result {
case .success:
completion(nil)
case .failure(let response):
completion(response.error)
}
}
```
Now:
```swift
networking.get("/somepath") { result in 
completion(result.error) // NSError?
}
```

Add error convenience accessor

---

Sources/Networking+Private.swift

There were some small changes to Swift 3.1 and new Xcode. Made appropriate changes and updates to silence compiler warnings

Updating to silence Swift 3.1 warnings

---

Sources/NetworkActivityIndicator.swift

When I change 
```
if UIApplication.responds(to: NSSelectorFromString("shared")) {
(UIApplication.value(forKeyPath: "shared") as? UIApplication)?.isNetworkActivityIndicatorVisible = (self.activitiesCount > 0)
}
```
To
```
if UIApplication.responds(to: NSSelectorFromString("sharedApplication")) {
(UIApplication.value(forKeyPath: "sharedApplication") as? UIApplication)?.isNetworkActivityIndicatorVisible = (self.activitiesCount > 0)
}
```
it works. Not sure why since it's `UIApplication.shared ` and not `UIApplication.sharedApplication`

Fixes #221 NetworkActivityIndicator not showing

---

Package.swift

There's a new set of [Swift Package Manager manifest format](https://github.com/apple/swift-package-manager/blob/master/Documentation/PackageDescriptionV4.md#target-format-reference). This commit should make `Networking` compliant.
Also, this PR would probably be a good place to discuss Linux compatibility 😬

Updated Package.swift

---

Sources/Networking+HTTPRequests.swift
Sources/Networking+Private.swift
Sources/Networking.swift
iOSDemo/FakeImageController.swift
iOSDemo/Info.plist

Allows the user to disable caching per request.
```swift
networking.downloadImage("/image/png", cachingLevel: .none) { result in
// Non-cached image....
}
```

Add support for caching level

---

Sources/Networking.swift
Tests/GETTests.swift
Tests/NetworkingTests.swift

Now you can do:
```swift
let networking = Networking()
networking.get("http://httpbin.org/get") { result in
// ....
}
```

Add support for skipping initializing with a url

---

Sources/Networking+Private.swift

PR in response to #248
- Use `assertionFailure` instead of `fatalError` for problems creating the cache url.
- Remove the explicit try! from `cacheOrPurgeJSON` call
- Added `@discardableResult` attribute to `cacheOrPurgeImage` so `let _ = ...` is no longer needed

Favor assert over fatalError in response to problems caching data

---

Package.swift

Since the current `swift-tools-version` in `Package.swift` is set to `4.0` it seems to create a problem when using `self.jpegData(compressionQuality: 1)` which was introduced in swift 4.2. 
This PR sets the `swift-tools-version` in `Package.swift` to 4.2

Set swift-tools-version to 4.2

---

Sources/Response.swift
Sources/Result.swift

Fixes #255
I would suggest instead fix json parsing so it is better suited of parsing of data returned from server as I pointed out in this bug report but I get over this problem by being able to access row body and parse it by myself.

Added row body to response so it can be used in cases when json parsing fail or posibly in other circumstances.

---

Sources/Networking/Networking+HTTPRequests.swift
Sources/Networking/Networking+New.swift
Tests/NetworkingTests/NewNetworkingTests.swift

Now supporting get parameters
