3lvis/Networking

Demo.xcodeproj/project.pbxproj
Source/Networking.swift
Tests/Tests.swift

Add support for cancelling requests

---

Networking.podspec
Source/Networking+Image.swift
Source/Networking.swift

Add Network Activity Indicator manager

---

Source/Networking.swift
Tests/HTTPRequestTests.swift

Add automatic validation

---

Demo.xcodeproj/project.pbxproj
Source/Dictionary+FormURLEncoded.swift
Source/Networking+HTTPRequest.swift
Source/Networking.swift
Tests/Dictionary+FormURLEncodedTests.swift
Tests/HTTPRequestTests.swift

Feature: FormURLEncoded

---

Source/Networking.swift

Improve cancelled request error logging

---

README.md
Source/Networking.swift

Replaces support for HTTP token with support for all kinds of authorization headers :tada:

Feature: custom authorization header

---

Source/Networking+Image.swift
Tests/ImageTests.swift

Supports downloading an image sending the full path, before the source url would have to be the same.

Feature: image download full path

---

Sources/Networking+Image.swift

Fix downloading images with special characters

---

Sources/Networking+HTTPRequest.swift
Tests/HTTPRequestTests.swift

Make POST parameters optional

---

Sources/Networking+Image.swift
Tests/ImageTests.swift

There was way too much duplicated code.

Refactor download image

---

Sources/Networking.swift
Tests/NetworkingTests.swift

Added basic data downloading method

---

Sources/Networking+HTTPRequest.swift
Sources/Networking.swift
Tests/POSTTests.swift

It was weird that the `Multipart` part was missing from the enum.

Rename FormData enum to MultipartFormData

---

Sources/Networking+DELETE.swift
Sources/Networking+GET.swift
Sources/Networking.swift
Tests/DELETETests.swift
Tests/GETTests.swift
Tests/POSTTests.swift
Tests/PUTTests.swift

I tested it with my logout request and now it works!
Solves #145

Set default parametertype to .none

---

Sources/FormDataPart.swift
Sources/Networking.swift

* Fix Multipart request not sending body when parameters is nil
* Make filename in FormDataPart optional

Fixing Multipart (#179)

---

Sources/Networking.swift

```swift
var configuration = URLSessionConfiguration.default
configuration.requestCachePolicy = .reloadIgnoringLocalCacheData
configuration.urlCache = nil
configuration.timeoutIntervalForRequest = TimeInterval(60)
configuration.timeoutIntervalForResource = TimeInterval(6048000)
let networking = Networking(baseURL: "http://httpbin.org", configuration: configuration)
```

Add support for initializing using a URLSessionConfiguration

---

Demo.xcodeproj/xcshareddata/xcschemes/iOSTests.xcscheme
Demo.xcodeproj/xcshareddata/xcschemes/macOSTests.xcscheme
Demo.xcodeproj/xcshareddata/xcschemes/tvOSTests.xcscheme
Sources/JSON.swift
Sources/Response.swift
Sources/Result.swift
Tests/JSONTests.swift
Tests/ResulTests.swift

Revert "Add support for data type and initial tests"

---

Demo.xcodeproj/project.pbxproj
Sources/Networking+HTTPRequests.swift
Sources/Networking+Private.swift
Sources/Networking.swift
Tests/FakeRequestTests.swift
Tests/PATCHTests.swift

Fixes https://github.com/3lvis/Networking/issues/219

Add PATCH support

---

Sources/Networking.swift
Tests/NetworkingTests.swift
iOSDemo/Assets.xcassets/AppIcon.appiconset/Contents.json

Updated missing directory paths

---

Sources/Networking+Private.swift

Remove crashing in purging

---

Package.swift
Sources/Networking/Networking+HTTPRequests.swift
Sources/Networking/Networking+Private.swift
Sources/Networking/Networking.swift
Tests/NetworkingTests/FakeRequestTests.swift
Tests/NetworkingTests/GETTests.swift
Tests/NetworkingTests/NetworkingTests.swift
Tests/NetworkingTests/PATCHTests.swift
Tests/NetworkingTests/ResponseTests.swift
Tests/NetworkingTests/ResultTests.swift

Add minimum deployment

---

Sources/Networking/FakeRequest.swift
Tests/NetworkingTests/FakeRequestTests.swift

Fix an issue with faking calls with patterns. Check tests for more information in how the errors were produced. The main culprit was iterating over a dictionary which is deterministic.

Fix faking with pattern

---

Sources/Networking/FakeRequest.swift
Sources/Networking/Networking+HTTPRequests.swift
Sources/Networking/Networking+Private.swift
Tests/NetworkingTests/FakeRequestTests.swift
Tests/NetworkingTests/GETTests.swift

Add delay to FakeRequests

---

Sources/Networking/Networking+HTTPRequests.swift
Sources/Networking/Networking+New.swift
Sources/Networking/Networking+Private.swift
Sources/Networking/Networking.swift

Initial version improved api

---

Sources/Networking/Networking+New.swift
Sources/Networking/Networking.swift

Improve logging

---

Sources/Networking/Networking+New.swift
Sources/Networking/NetworkingJSON.swift

Networking json

---

Sources/Networking/JSON.swift
Sources/Networking/Networking+HTTPRequests.swift
Sources/Networking/Networking+New.swift
Sources/Networking/Networking+Private.swift
Sources/Networking/NetworkingResult.swift
Sources/Networking/Response.swift
Tests/NetworkingTests/GETTests.swift
Tests/NetworkingTests/JSONTests.swift
Tests/NetworkingTests/NewNetworkingTests.swift
Tests/NetworkingTests/ResultTests.swift

Improve Fake handling, add status code to faking with a file.
